name: Storm CMS Page Builder
description: Enhances the page building experience with Drupal Layout Builder
recipes:
  - storm_cms_content_type_base
install:
  - layout_builder
  - layout_builder_browser
  - layout_builder_modal
  - layout_builder_operation_link
  - layout_builder_restrictions
  - media_library_form_element
  - section_library
  - storm_cms_layout_builder
config:
  import:
    layout_builder_browser: "*"
    layout_builder_restrictions: "*"
    section_library: "*"
    storm_cms_layout_builder: "*"
  actions:
    layout_builder_browser.settings:
      simple_config_update:
        use_modal: true
    layout_builder_modal.settings:
      simple_config_update:
        modal_width: "1160"
        use_modal:
          add_block: add_block
          choose_block: choose_block
          choose_section: choose_section
          configure_section: configure_section
          remove_block: remove_block
          remove_section: remove_section
          update_block: update_block
          choose_inline_block: choose_inline_block
    metatag.settings:
      simple_config_update:
        entity_type_groups.node.landing_page:
          - basic
          - advanced
          - open_graph
          - twitter_cards
    workflows.workflow.editorial:
      addNodeTypes:
        - landing_page
